<?php
/* 
 * @category  Event Manager Module
 * @package   Piyush_Events
 * @author    Piyush Kumar <phpteamlead.mca@gmail.com,er.piyush.kumar@gmail.com>
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @link      N/A 
 */
?>
<?php $_eventsItem = $this->helper('piyush_events')->getEventsItemInstance(); ?>
<div id="events_item_messages"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>

<div class="page-title">
    <h1><?php echo $this->escapeHtml($_eventsItem->getTitle()) ?></h1>

    <div class="events_item_subtitle">
        <?php echo $this->formatDate($_eventsItem->getTimePublished(), Mage_Core_Model_Locale::FORMAT_TYPE_MEDIUM) ?> 
         <?php echo "<br/>Venue Details: ". $this->escapeHtml($_eventsItem->getVenue())?> 
		<?php echo "<br/>Entry Fee: ".Mage::helper('core')->currency($_eventsItem->getEntryFee()); ?>
    </div>
	
</div>

<div class="events_item_view">
    <?php if ($imageUrl = $this->getImageUrl($_eventsItem, 400)): ?>
       <p><img src="<?php echo $imageUrl ?>" alt="<?php echo $this->escapeHtml($_eventsItem->getTitle()) ?>" /></p>
    <?php endif; ?>
    <div class="events_item_content"><span style="font-size:14px;font-weight:bold">Event Details</span><br/><?php echo $_eventsItem->getDetails(); ?></div>
	 <div class="events_item_content"><span style="font-size:14px;font-weight:bold">Eligibility</span><br/><?php echo $_eventsItem->getEligibility(); ?></div>

    <div class="pager">
        <a href="<?php echo $this->getBackUrl() ?>">
            <?php echo Mage::helper('piyush_events')->__('Return to list') ?>
        </a>
    </div>
</div>
